name: Greetings

on: [pull_request_target, issues]

permissions: {}

jobs:
  greeting:
    uses: hoverkraft-tech/ci-github-common/.github/workflows/greetings.yml@666b7b6eb000db3e8614647871fa60c9f1eb7179 # 0.31.4
    permissions:
      contents: read
      issues: write
      pull-requests: write
