name: Greetings

on: [pull_request_target, issues]

permissions: {}

jobs:
  greeting:
    uses: hoverkraft-tech/ci-github-common/.github/workflows/greetings.yml@5ac504609f6ef35c5ac94bd8199063aa32104721 # 0.31.3
    permissions:
      contents: read
      issues: write
      pull-requests: write
